apiVersion: v1
kind: Pod
metadata:
  name: insecure-pod
spec:
  containers:
    - name: insecure-container
      image: nginx:latest
      securityContext:
        privileged: true
        runAsUser: 0
        allowPrivilegeEscalation: true
        capabilities:
          add: ["ALL"]
